source 'https://rubygems.org'

gem 'rack-contrib'
gem 'builder'
gem 'capistrano', '>= 2.0', '< 3.0'
gem 'haml'
gem 'hpricot'
gem 'middleman', '>= 3.0', '< 4.0'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'middleman-bourbon'
gem 'redcarpet', '>= 2', '< 3'
gem 'sass'
gem 'therubyracer'
