source 'https://rubygems.org'

gem 'builder'
gem 'capistrano'
gem 'haml'
gem 'hpricot'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'middleman-bourbon'
gem 'redcarpet'
gem 'sass'
gem 'therubyracer'
